"""empty message

Revision ID: 0c431c58ec07
Revises: bc363ad57e43
Create Date: 2020-02-24 18:47:27.539491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c431c58ec07'
down_revision = 'bc363ad57e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment_details',
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('number_of_wings', sa.Integer(), nullable=True),
    sa.Column('number_of_floors', sa.Integer(), nullable=True),
    sa.Column('number_of_flats', sa.Integer(), nullable=True),
    sa.Column('total_flats', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('apartment_id')
    )
    op.create_table('management_contact_info',
    sa.Column('management_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('management_id')
    )
    op.drop_column('building_details', 'society_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building_details', sa.Column('society_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('management_contact_info')
    op.drop_table('apartment_details')
    # ### end Alembic commands ###
