"""empty message

Revision ID: 2199434281bf
Revises: 65843ef94271
Create Date: 2020-02-25 09:14:32.864806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2199434281bf'
down_revision = '65843ef94271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('society', sa.Column('management_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'society', 'management', ['management_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'society', type_='foreignkey')
    op.drop_column('society', 'management_id')
    op.drop_table('management')
    # ### end Alembic commands ###
