"""empty message

Revision ID: 30aff0423eda
Revises: 7c4031cb165f
Create Date: 2020-02-24 09:47:52.438451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30aff0423eda'
down_revision = '7c4031cb165f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token_table',
    sa.Column('access_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('access_token')
    )
    op.drop_column('user', 'access_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('access_token_table')
    # ### end Alembic commands ###
