"""empty message

Revision ID: 384fbd82c354
Revises: 3bbb72402d06
Create Date: 2020-02-21 12:43:40.915569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384fbd82c354'
down_revision = '3bbb72402d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
