"""empty message

Revision ID: 5aeeb07dd942
Revises: 30aff0423eda
Create Date: 2020-02-24 15:02:59.159516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aeeb07dd942'
down_revision = '30aff0423eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('society_details',
    sa.Column('society_id', sa.String(), nullable=False),
    sa.Column('society_type', sa.String(), nullable=True),
    sa.Column('is_fenced', sa.String(), nullable=True),
    sa.Column('is_guarded', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('society_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('society_details')
    # ### end Alembic commands ###
