"""empty message

Revision ID: 9f15e06c85c6
Revises: f927a5cffff0
Create Date: 2020-02-21 12:26:15.287272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f15e06c85c6'
down_revision = 'f927a5cffff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    op.add_column('user', sa.Column('user_email', sa.String(), nullable=True))
    op.add_column('user', sa.Column('user_name', sa.String(), nullable=True))
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'email')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'user_name')
    op.drop_column('user', 'user_email')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
