"""empty message

Revision ID: bc363ad57e43
Revises: 5aeeb07dd942
Create Date: 2020-02-24 15:06:36.197497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc363ad57e43'
down_revision = '5aeeb07dd942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_details',
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=True, foreign_key=True),
    sa.Column('number_of_floors', sa.Integer(), nullable=True),
    sa.Column('number_of_flats', sa.Integer(), nullable=True),
    sa.Column('total_flats', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('building_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('building_details')
    # ### end Alembic commands ###
