"""empty message

Revision ID: c4d3bae9e6b9
Revises: ceb98c6c43f3
Create Date: 2020-02-24 19:31:20.767299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d3bae9e6b9'
down_revision = 'ceb98c6c43f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('building_details')
    op.drop_table('society_details')
    op.drop_table('apartment_details')
    op.drop_table('management_contact_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management_contact_info',
    sa.Column('management_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('management_id', name='management_contact_info_pkey')
    )
    op.create_table('apartment_details',
    sa.Column('apartment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number_of_wings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_of_floors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_of_flats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_flats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('apartment_id', name='apartment_details_pkey')
    )
    op.create_table('society_details',
    sa.Column('society_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('society_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_fenced', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_guarded', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('society_id', name='society_details_pkey')
    )
    op.create_table('building_details',
    sa.Column('building_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number_of_floors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_of_flats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_flats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('building_id', name='building_details_pkey')
    )
    # ### end Alembic commands ###
