"""empty message

Revision ID: ceb98c6c43f3
Revises: 0c431c58ec07
Create Date: 2020-02-24 19:10:56.088244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb98c6c43f3'
down_revision = '0c431c58ec07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building_details', sa.Column('society_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'building_details', 'society_details', ['society_id'], ['society_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'building_details', type_='foreignkey')
    op.drop_column('building_details', 'society_id')
    # ### end Alembic commands ###
