"""empty message

Revision ID: f9fcc2057e92
Revises: 24b3540ed9f7
Create Date: 2020-02-24 09:38:38.932869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fcc2057e92'
down_revision = '24b3540ed9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token_table',
    sa.Column('access_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('access_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_token_table')
    # ### end Alembic commands ###
